services:
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./docker/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  postgresql:
    image: postgres:latest
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  rabbitmq:
    image: rabbitmq:latest
    ports:
      - "15672:15672"
      - "5672:5672"

  grafana:
    image: grafana/grafana-enterprise:latest
    volumes:
      - grafana-storage:/var/lib/grafana
    ports:
      - "3000:3000"

  go_server:
    image: go_server
    ports:
      - "5001:5001"
      - "2222:2222"

volumes:
  postgres:
  grafana-storage: