services:
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./docker/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    expose:
      - "2222"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  postgresql:
    image: postgres:latest
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  rabbitmq:
    image: rabbitmq:latest
    ports:
      - "5672:5672"
      - "15672:15672"

  grafana:
    image: grafana/grafana-enterprise:latest
    volumes:
      - grafana-storage:/var/lib/grafana
    ports:
      - "3000:3000"

volumes:
  postgres:
  grafana-storage: